### ISSUE TITLE
It doesn't work on Python 3.8.10

### ISSUE THREAD

**Issue by acccccccb** [gryf/ebook-converter#5]
It doesn't work, i want convert .txt to .epub/.mobi without gui and use it in Calibre-Web

System: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)
Python 3.8.10

type

```ebook-converter ebook.txt ebook.epub```

return

> Traceback (most recent call last):
  File "/home/workspace/venv/bin/ebook-converter", line 8, in <module>
    sys.exit(run())
TypeError: run() missing 1 required positional argument: 'args'

```cat /home/workspace/venv/bin/ebook-converter/ebook-converter```

``` # -*- coding: utf-8 -*-
import re
import sys
from ebook_converter.main import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

**Comment by gryf** [comment]
Thanks for the report!

I've recently changed main function, and forgot to change that in setup. Fixed in 76e604c951d929e443cb0cd09d397c6a305d7e19.
